### ISSUE TITLE
Klasör, project ve solution isimleri düzletilmeli

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#1]
task1 gibi bir adlandırma çok doğru değil.

örnek kargo firmamızın adı "bynrcargo".
solution adı: "bynrcargo"
project adı: "bynrcargo.Api" olmalı.

**Comment by bgbl1** [comment]
task1 projesinin adı bynrcargo.Api olarak değiştirildi , solution name düzeltildi.
