### ISSUE TITLE
namespace'lerde hala task1 yazıyor. bu düzeltilmeli

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#12]
https://github.com/bgbl1/webapi-deneme/blob/1a5eb81055b928aa5c70a41d8c528b67fe38b767/bynrcargo.Api/bynrcargo.Api/Controllers/DeliveryController.cs#L11

**Comment by bgbl1** [comment]
Düzelt: Namespacelerdeki task1 adlandırması  "Delivery" olarak güncellendi.(#12)
