### ISSUE TITLE
burada 404 dönmemiz lazım

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#13]
https://github.com/bgbl1/webapi-deneme/blob/1a5eb81055b928aa5c70a41d8c528b67fe38b767/bynrcargo.Api/bynrcargo.Api/Controllers/DeliveryController.cs#L27

**Comment by bgbl1** [comment]
Düzelt: Teslimat listesi boşken 404 HTTP Status Code döndürüldü. (#13)
