### ISSUE TITLE
Property isimleri csharp'ın büyük küçük harf standartlarına uygun değil

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#15]
https://github.com/bgbl1/webapi-deneme/blob/a132fda9182a9e2bb6f9a05ae71ad9c9b47c0643/bynrcargo.Api/bynrcargo.Api/Controllers/Delivery.cs#L6

**Comment by bgbl1** [comment]
PascalCase'e uygun olarak mı düzeltmem gerekiyor?(#15)

**Comment by bgbl1** [comment]
Güncelle: Property isimleri c# ın büyük-küçük harf standartlarına uygun şekilde güncellendi.(#15)
