### ISSUE TITLE
burada tekrar firstordefault yapmana gerek yok. zaten elinde bir delivery var. onu return etmelisin

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#20]
https://github.com/bgbl1/webapi-deneme/blob/a9893d6c48e9b875bf7cb12ada5c4fa26c7a3b99/bynrcargo.Api/bynrcargo.Api/Controllers/DeliveryController.cs#L67

**Comment by bgbl1** [comment]
Düzeltme: firsordefault kaldırıldı mevcut delivery return edildi.
