### ISSUE TITLE
Delivery.Status'un tipi şuan string. bunu enum yapalım

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#21]
https://github.com/bgbl1/webapi-deneme/blob/a9893d6c48e9b875bf7cb12ada5c4fa26c7a3b99/bynrcargo.Api/bynrcargo.Api/Controllers/Delivery.cs#L10

statuler şunlar olsun:

Created,
InTransit,
Delivered,
NotDelivered

**Comment by bgbl1** [comment]
Güncelle: Delivery.Status type'ı enum olarak güncellendi ve default created olarak ayarlandı.Belirtilen statuler enum listesine eklendi (#21)
