### ISSUE TITLE
Get metotlarının düzenlenmesi

### ISSUE THREAD

**Issue by asyailkturk** [bgbl1/webapi-deneme#22]
Burada iki adet get metodumuz var, aslında ikisinin farklı işlevi var. Bu tarz durumlarda isimlendirmeyi değiştirebiliriz. (Örn :get ve get all ).

**Comment by bgbl1** [comment]
Güncelle: Get metodlarının işlevine göre adlandırılıp isimlendirmesi değiştirildi.(#22)
