### ISSUE TITLE
Burada neden bunu dönüyoruz?

### ISSUE THREAD

**Issue by asyailkturk** [bgbl1/webapi-deneme#24]
https://github.com/bgbl1/webapi-deneme/blob/c7314e179de3c93ee829dab7ead990939ce0f6b6/bynrcargo.Api/bynrcargo.Api/Controllers/DeliveryController.cs#L66C12-L66C28

**Comment by bgbl1** [comment]
iptal edilen deliveryi kullanıcıya göstermek için.

**Comment by bgbl1** [comment]
Düzelt: İptal edilen deliveryi döndürmek yerine iptal işlemini onaylandığını belirtmek için 202 dönmesi sağlandı.(#24)

**Comment by asyailkturk** [comment]
bence de böylesi daha güzel, eline sağlık
