### ISSUE TITLE
refactor & bugfix

### ISSUE THREAD

**Issue by asyailkturk** [bgbl1/webapi-deneme#25]
https://github.com/bgbl1/webapi-deneme/blob/c7314e179de3c93ee829dab7ead990939ce0f6b6/bynrcargo.Api/bynrcargo.Api/Controllers/DeliveryController.cs#L50C17-L62C43

50. ve 62. satırlarda aslında ikisinde de not found dönüyorsun, bunları ortaklaştırmak daha iyi olur. 50. satırdaki kullanım daha doğru. birinde hatta return etmiyorsun, return etmediğin için kod alt satırlara iniyor. bunları kodu debug ettiğinde daha net görüyor olursun. #23  aslında bu issueda bahsetmek istediğim biraz da bu konulardı :)

**Comment by bgbl1** [comment]
Düzelt: Http Status Code responsları 50. satırda olduğu gibi doğru bi şekilde bütün kodda ortak olarak kullanıldı.(#25)
