### ISSUE TITLE
Burada anonymous type return edilerek problem çözülmüş ancak yeni bir tip oluşturup belli bir tipi dönmemiz daha sağlıklı

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#26]
https://github.com/bgbl1/webapi-deneme/blob/c7314e179de3c93ee829dab7ead990939ce0f6b6/bynrcargo.Api/bynrcargo.Api/Controllers/DeliveryController.cs#L52

**Comment by bgbl1** [comment]
Düzelt: Anonymous type sorununu gidermek için DeliveryInfo adında bir class tanımlandı ve ondan üretilen değişkenle return edildi. (#26)
