### ISSUE TITLE
Kod, CSharp yazım standartlarına uygun şekilde yazılmalı

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#5]
Bu örnekte `Shipment` ismiyle tanımlanan nesne bir field. Fieldlar camelCase tanımlanır.
`shipment` veya `_shipment` şeklinde tanımlanabilir.

https://github.com/bgbl1/webapi-deneme/blob/dbe06f630d994aa5f46a324476f87aa3edd959b9/task1/task1/Controllers/CargoController.cs#L10C32-L10C41

**Comment by bgbl1** [comment]
Field name düzeltildi.
