### ISSUE TITLE
Gönderiyi iptal etme endpointi yazılmalı

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#6]
`base-url/Delivery/Cancel?deliveryCode=123`

yukarıdaki belirtilen şekilde bir gönderi iptal endpointi yazılmalı.
eğer gönderi bulunamazsa statuscode: 404
gönderi başarılı şekilde iptal edilirse statuscode: 200

**Comment by bgbl1** [comment]
cancel endpointi yazıldı.
