### ISSUE TITLE
Controller adı ve model ismi uyumsuz

### ISSUE THREAD

**Issue by tolgacakir** [bgbl1/webapi-deneme#7]
Controller adı CargoController ancak yapılan işlemler, Delivery class'ı üzerinden yapılıyor.
Ayrıca içeride bir de `List<Delivery> shipment` tanımlanmış.
İsimlendirme konusu bir standarta oturtulmalı.

bu 3 isimden biri tercih edilip o isim verilmeli.

**Comment by bgbl1** [comment]
Controller adı ve model ismi uyumlu hale getirildi.
