### ISSUE TITLE
Endpointler http status code dönebilir

### ISSUE THREAD

**Issue by asyailkturk** [bgbl1/webapi-deneme#8]
Duruma, sonuca uygun status code dönebiliriz.

https://http.cat/  :)

**Comment by bgbl1** [comment]
Bazı durumlara uygun statuscodelar eklendi.

**Comment by tolgacakir** [comment]
bağzı mı :)

**Comment by asyailkturk** [comment]
bundan sonra bütün de'leri ayrı şey'leri birleşik yazıyoruz, Tolga'nın çok hoşuna gider :D

**Comment by bgbl1** [comment]
Güncelleme : Dikkatsizce yazılan "bağzı" kelimesi "bazı" olarak güncellendi :)
